input.onButtonPressed(Button.A, function () {
    basic.showString("hallo!")
    music.playMelody("E B C5 A B G A F ", 120)
    basic.showIcon(IconNames.Pitchfork)
    basic.showString("" + (led.point(3, 3)))
    led.unplot(3, 3)
})
input.onButtonPressed(Button.AB, function () {
    RingbitCar.running_time(RingbitCar.Direction_run.forward, 20)
    RingbitCar.running_time(RingbitCar.Direction_run.backward, 20)
    basic.showString("bay bay")
    RingbitCar.brake()
})
input.onButtonPressed(Button.B, function () {
    RingbitCar.steering_angle(RingbitCar.Direction_turn.right, 90)
    basic.showString("jeg har laget dette selv")
    basic.showArrow(ArrowNames.North)
    basic.showArrow(ArrowNames.NorthEast)
    basic.showArrow(ArrowNames.East)
    basic.showArrow(ArrowNames.SouthEast)
    basic.showArrow(ArrowNames.South)
    basic.showArrow(ArrowNames.SouthWest)
    basic.showArrow(ArrowNames.West)
    basic.showArrow(ArrowNames.NorthWest)
})
